version: '3'
services:
  httpd:
    env_file: .env
    container_name: myapache
    build:
      context: .
      dockerfile: Dockerfile_apache
    ports:
      - ${HOST_APACHE_PORT}:${CONTAINER_APACHE_PORT}

  myfastapi:
    env_file: .env
    container_name: myroboatcontainer
    volumes:
      - ${HOST_DATA_PATH}:${CONTAINER_WORKING_DIR}/Data
      - ${HOST_LOGS_PATH}:${CONTAINER_WORKING_DIR}/Logs
    build:
      context: .
      dockerfile: Dockerfile_roboatapi
    ports:
      - "${UVICORN_PORT_NUMBER}:${UVICORN_PORT_NUMBER}"
    network_mode : host
    command: uvicorn roboatAPI:app --host ${HOST_DOMAIN_NAME} --port ${UVICORN_PORT_NUMBER}

